blog/urls.py
# Use include() to add paths from the catalog application
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
]

django_mini_blog/urls.py
from django.contrib import admin
from django.urls import path

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('blog/', include('blog.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse 
from django.contrib.auth.models import User 
from django.utils import timezone


'''
Each comment will have only one blog, but a blog may have many comments.
Blog posts and comments must be sorted by post date.
Not every user will necessarily be a blog author though any user may be a commenter.
Blog authors must also include bio information.'''


# Model representing a blog author

class BlogAuthor(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text='Enter your bio details here.')
    
    class Meta:
        ordering = ["user", "bio"]
        
    def get_absolute_url(self):
        return reverse('blogs-by-author', args=[str(self.id)])
    
    def __str__(self):
        return self.user.username
    
    
# Model representing a blog post

class Blog(models.Model):    
    name = models.CharField(max_length=200)
    # Blog only have 1 author/user, but bloggers have mutiple blog posts
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=2000, help_text = "Enter your blog text here.")
    post_date = models.DateField(default=timezone.now)
    
    class Meta:
        ordering = ["-post_date"]
    def get_absolute_url(self):
        return reverse("blog-detail", args=[str(self.id)])
    def __str__(self):
        return self.name
    
    

class BlogComment(models.Model):
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    # Blog Comment only have 1 author/user, but users have mutiple comments
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_date=models.DateTimeField(auto_now_add=True)
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE) #A foreign key linking to Blog. If the blog is deleted, the comment is also deleted.
    
    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        '''Returns a truncated version of the comment description for display, up to 75 characters.'''
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

blog/views.py
from django.shortcuts import render
def index(request):
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'index.html', {'num_visits': num_visits})
# Create your views here.

from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.contrib.auth.models import User #Blog author or commenter

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5
    
from django.shortcuts import get_object_or_404

class BlogListbyAuthorView(generic.ListView):

    model = Blog
    paginate_by = 5
    template_name ='blog/blog_list_by_author.html'
    
    def get_queryset(self):

        id = self.kwargs['pk']
        target_author=get_object_or_404(BlogAuthor, pk = id)
        return Blog.objects.filter(author=target_author)
        
    def get_context_data(self, **kwargs):

        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        context['blogger'] = get_object_or_404(BlogAuthor, pk = self.kwargs['pk'])
        return context


class BlogDetailView(generic.DetailView):
    model = Blog


class BloggerListView(generic.ListView):
    model = BlogAuthor
    paginate_by = 5


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

# Form for adding a blog cmt
class BlogCommentCreate(LoginRequiredMixin, CreateView):
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Mini Blog</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'blogs' %}">All blogs</a></li>
                <li><a href="{% url 'bloggers'%}">All bloggers</a></li>
            </ul>

            <ul class="sidebar-nav">
                {% if user.is_authenticated %}
                  <li>User: {{ user.get_username }}</li> <!-- Corrected from user.get_username to user.get_username() -->
                  <li>
                   <form id="logout-form" method="post" action="{% url 'logout' %}"> <!-- Assuming default logout view -->
                     {% csrf_token %}
                     <button type="submit" class="btn btn-link">Logout</button>
                   </form>
                 </li>  
                {% else %}
                  <li><a href="{% url 'login'%}?next={{ request.path }}">Login</a></li> <!-- Ensure request.path exists in context -->
                {% endif %} 
               </ul>
            {% endblock %}
        </div>
        
        <div class="col-sm-10">
            {% block content %}
            <!-- Content goes here -->
            {% endblock %}

            {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
            {% endblock %}
        </div> <!-- Closing div for col-sm-10 -->
    </div> <!-- Closing div for row -->
</div> <!-- Closing div for container-fluid -->

</body>
</html>

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>All blogs</h1>

  {% if blog_list %}
  <ul>
    {% for blog in blog_list%}
    <li>
      <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
    </li>
    {% endfor %}
  </ul>

  {% else %}
    <p> There are no blogs.</p>
  {% endif %}

{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger: {{blogger}}</h1>
  <h3>Bio</h3>
  <p>{{blogger.bio}}</p>


  {% if blog_list %}
  <h3>Blogs list</h3>

  <ul>
    {% for blog in blog_list %}
    <li>
      <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
    </li>
    {%endfor%}
  </ul>

    {% else %}
    <p> This blogger hasn't posted anything yet. </p>
    {% endif %}

{%endblock%}

blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html"%}

{%block content%}
    <h1> All bloggers</h1>

    {% if blogauthor_list%}
    <ul>
        {% for author in blogauthor_list%}
        <li>
            <a href="{% url 'blogs-by-author' author.pk %}">{{author}}</a>
        </li>
        {% endfor%}

    </ul>

    {%else%}
        <p> There are no bloggers yet.</p>
    {% endif%}

{%endblock%}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/index.html
{% extends 'base_generic.html' %}

{% block content %}
<div style="text-align: center; margin-bottom: 20px;">
    <img src="https://www.martinasclassesgoldcoast.com/uploads/4/2/6/6/42666647/bannerblog1000x300dark_orig.jpg" alt="Mini Blog Banner" style="width: 100%; height: auto;">
</div>

<div>
    <h2 style="color: #2c3e50; text-align: center;">MINI BLOG</h2>
    <p style="text-align: center; font-size: 18px;">
        Welcome to Mini Blog, a website developed by
        <strong>Hang Nguyen</strong>!
      </p>
</div>

<div>
    <div>
        <h4>Start Your Blogging Journey Today</h4>
        <ul>
            <li>MiniBlog offers you a simple and elegant platform to share your thoughts and stories with the world. Whether you're a seasoned writer or just starting out, you'll find our tools and features easy to use and incredibly effective.</li>
            <li>Join our community of passionate bloggers, explore a variety of topics, and get inspired by others. With MiniBlog, your voice can reach a global audience.</li>
            <li>Go ahead! Create an account and start blogging!</li>
        <ul>
    </div>
</div>

<p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>

{% endblock %}